### PR TITLE
Drop subtables with empty coverage.

### LINKED ISSUE #90: Overflow error: "OT layout lookup with empty coverage"
---

Original discussion in zulip: https://xi.zulipchat.com/#narrow/channel/205635-parley/topic/Font.20causing.20overflow.20error.20in.20swash/with/508288770

> Looks like this is caused by an OT layout lookup with empty coverage. Should be a simple fix in swash. - @dfrg 

---

The font in https://github.com/bevyengine/bevy/tree/v0.15.3/crates/bevy_text/src causes overflow errors in swash; I don't know how to move forward with this issue with my limited knowledge about the parley and swash stack, whether it's a bug or bad ttf file, or just a config or something else.

Works fine with the font here: https://github.com/RobertBrewitz/bevy_vello/tree/robertbrewitz/parley/examples/text/src/assets

```bash
thread 'Compute Task Pool (3)' panicked at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/at.rs:572:25:
attempt to subtract with overflow

  16:     0x5c7014693122 - swash::shape::at::CoverageBuilder::finish::h64674091fe502906
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/at.rs:572:25
  17:     0x5c7014690e27 - swash::shape::at::FeatureStoreBuilder::build_stage::h67e64250302e9241
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/at.rs:482:39
  18:     0x5c70146901ea - swash::shape::at::FeatureStoreBuilder::build::h06d1ae0c47105346
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/at.rs:389:13
  19:     0x5c7014651335 - swash::shape::engine::Engine::collect_features::hd68e9f7e2f3bf382
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/engine.rs:109:9
  20:     0x5c701465276e - swash::shape::ShaperBuilder::build::hb3acb816d488eafc
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/mod.rs:539:21
  21:     0x5c7014507d19 - swash::shape::partition::shape_clusters::hb76f699e4ec70fec
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/partition.rs:219:22
  22:     0x5c7014508b47 - swash::shape::partition::shape::h3a326b285ac7ef36
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swash-0.2.1/src/shape/partition.rs:186:15
  23:     0x5c70145e44e8 - parley::shape::shape_text::h3413686bc7e23473
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parley-0.3.0/src/shape.rs:110:13
  24:     0x5c7014506598 - parley::builder::build_into_layout::h07411d1c792806cd
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parley-0.3.0/src/builder.rs:172:9
  25:     0x5c70145067ba - parley::builder::RangedBuilder<B>::build_into::h21a4ca986eeda68d
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parley-0.3.0/src/builder.rs:55:9
  26:     0x5c70145069d2 - parley::builder::RangedBuilder<B>::build::h5807bb83db61d879
                               at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parley-0.3.0/src/builder.rs:60:9
```

### PR DESCRIPTION
**Pull request by xorgy**
Empty subtables are useless, and coverage is expected not to be empty elsewhere in Swash (particularly in `CoverageBuilder`).

This change now treats empty subtables as invalid which prevents lookups on empty subtables from propagating.

### CODE REVIEW

File: src/internal/at.rs [hunk 1]
```diff
@@ -822,30 +818,17 @@ pub fn subtable_data(b: &Bytes, offset: u32, kind: LookupKind, fmt: u16) -> Opti
...
-                None
-            } else {
-                Some(())
-            }
-        }
-        _ => None,
+    match (b.read::<u16>(base), b.read::<u16>(base + 2)) {
+        (Some(_), Some(0)) => false,
+        (Some(1), Some(len)) => !!b.check_range(arr, len as usize * 2),
+        (Some(2), Some(len)) => !!b.check_range(arr, len as usize * 6),
```
Comment (nicoburns) [inline src/internal/at.rs:830]: The double negations (`!!`) could be removed I think

Comment (xorgy) [reply src/internal/at.rs:830]: No, check_range returns a nonempty option, this coerces it to a bool.

**Review by nicoburns — APPROVED** [review]
Ah yes. I knew there must be a change in there somewhere! I am not familiar with this code or format, but this change makes sense to me.

File: src/internal/at.rs [hunk 2]
```diff
@@ -822,30 +818,17 @@ pub fn subtable_data(b: &Bytes, offset: u32, kind: LookupKind, fmt: u16) -> Opti
...
-        2 => {
-            if !b.check_range(arr, len * 6) {
-                None
-            } else {
-                Some(())
-            }
-        }
-        _ => None,
+    match (b.read::<u16>(base), b.read::<u16>(base + 2)) {
+        (Some(_), Some(0)) => false,
```
Comment (waywardmonkeys) [inline src/internal/at.rs:828]: I'd like to just see a comment here that this is explicitly dropping empty tables (such as might result from a font subsetter).

The simplification to this code is nice though!

**Review by waywardmonkeys — APPROVED** [review]
LGTM after a comment is added.

File: src/internal/at.rs (hunk 1 above)
Comment (waywardmonkeys) [inline src/internal/at.rs:830]: Having `!!b` on a small screen is hard to read and makes me have to look at the return type of `check_range` ... it might be that this could be clearer with `is_some`.

Comment (waywardmonkeys) [reply src/internal/at.rs:830]: Except it is a bool return, so this extra stuff isn't needed! :)

Comment (xorgy) [reply src/internal/at.rs]: Sorry for gaslighting you about this @nicoburns, I thought for sure clippy would be complaining when I went and checked again.
